services:
  postgres:
    image: postgres:13
    container_name: kpa_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kpa_network

volumes:
  postgres_data:

networks:
  kpa_network:
    driver: bridge
